<?php
include __DIR__ . '/inc/config.inc.php';
$home = true;
$interna = false;
$recaptcha = false;
$breadcrumb = false;
$compartilhar = false;
$titulo = 'Home';
$ocultartitulo = true;
$tags = false;
$gestor = false;
$maisvisitados = false;
include __DIR__ . '/inc/header.inc.php';
include __DIR__ . '/inc/home/destaques-topo.inc.php';
// print '<div class="servicos-destaques__conteudo"><div class="servicos-destaques__linha">';
// include __DIR__ . '/inc/home/servicos.inc.php';
// include __DIR__ . '/inc/home/destaques-temas.inc.php';
// print '</div></div>';
include __DIR__ . '/inc/home/destaques-temas-novo.inc.php';
include __DIR__ . '/inc/home/full-cards.inc.php';
include __DIR__ . '/inc/home/redes-sociais.inc.php';
// include __DIR__ . '/inc/home/cards-social-media.inc.php';
include __DIR__ . '/inc/home/banners-home.inc.php';
include __DIR__ . '/inc/home/modal-servicos-eleitor.inc.php';
include __DIR__ . '/inc/home/modal-consultas.inc.php';
include __DIR__ . '/inc/home/modal-dje.inc.php';
include __DIR__ . '/inc/footer.inc.php';
